### ISSUE TITLE
[Bug]: "Shits" (or maybe bads) sometimes not working

### ISSUE THREAD

**Issue by SpunBlue** [SpunBlue/NUFNF#2]
### Contact Details

SpunBlue#8248

### What happened?

Basically if you hit a note a very VERY certain way, You will miss. Even though the note is overlapping the player... note... sprite thingies.

Video: https://www.youtube.com/watch?v=rzLibJYVg0o&ab_channel=SpunBlue

### Steps to reproduce

"Basically if you hit a note a very VERY certain way, You will miss. Even though the note is overlapping the player... note... sprite thingies."

### Version

2.1.0

**Comment by thepercentageguy** [comment]
u forgot to close the issue
